-- The app does not use Supabase Auth.
-- Run these files, in order, in the Supabase SQL editor:
--   supabase_profiles.sql
--   supabase_pantry.sql
--   supabase_shopping.sql
--
-- All use permissive anon policies. That is demo-grade only.
