-- The app does not use Supabase Auth.
-- Run these files, in order, in the Supabase SQL editor:
--   supabase_profiles.sql
--   supabase_pantry.sql
--   supabase_shopping.sql
--   supabase_imported_recipes.sql
--
-- Profiles, pantry, and shopping use permissive anon policies. That is
-- demo-grade only. imported_recipes is separate from any shared catalog
-- and allows a row only when user_id matches the x-profile-id header.
